name: Tests

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - "**"

env:
  FORCE_COLOR: 2

jobs:
  run:
    name: Node
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "16.x"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run testpr
